language: csharp
mono: none
dotnet: 3.1
branches:
  only:
  - master
  - develop
install:
 - dotnet restore
script:
 - dotnet build NeoServer.sln
 - dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)
