name: OpenCoreMMO
run-name: OpenCoreMMO Workflow validation
on:
  push:
  pull_request:
    branches: [ develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/*.yaml'
      - '**/*.yml'
jobs:
  workflow:
    uses: ./.github/workflows/_workflow.yaml
    with:
      path: /
      project: src/Standalone
      test: src
      deploy: true